services:
  postgres:
    image: postgres:15
    container_name: postgres_evolution
    restart: always
    environment: # credenciales de ejemplo, recomendado cambiar
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=evolution_db
    ports:
      - "5433:5432" # Si tienen una bdd aparte dejar el primer puerto
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_evolution
    restart: always
    ports:
      - "6379:6379" # Mapeo de puertos para que NVM lo vea
    command: redis-server --appendonly yes