services:
  postgres:
    image: postgres:15
    container_name: postgres_evolution
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=evolution_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_evolution
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  # --- NUEVO SERVICIO AGREGADO ---
  browserless:
    image: ghcr.io/browserless/chromium:latest
    container_name: browserless_chrome
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - DEBUG=browserless*
      # --- AGREGAR ESTO PARA EVADIR DETECCIÃ“N ---
      - STEALTH_EVASIONS=1         # Activa plugins para ocultar que es un bot
      - HEADLESS=false             # A veces ayuda simular que tiene cabeza (aunque corre en servidor)
      - ENABLE_CORS=true
      - KEEP_ALIVE=true
      - CONNECTION_TIMEOUT=300000  # 5 minutos de timeout
    shm_size: '2gb'